apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgreses.cloudprov.org
spec:
  group: cloudprov.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                databaseName:
                  type: string
            status:
              type: object
              properties:
                provisioningStatus:
                  type: string
                databaseName:
                  type: string
                userName:
                  type: string
  names:
    kind: Postgres
    plural: postgreses
  scope: Namespaced
