apiVersion: cloudprov.org/v1alpha1
kind: Postgres
metadata:
  name: example-postgres-dynamic
---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: postgres-tester
    image: widmaster/postgres-provisionner
    command: [ "sh", "-c", "sleep 3600" ]
    envFrom:
      - secretRef:
          name: example-postgres-dynamic
  restartPolicy: Never
