apiVersion: v1
metadata:
  name: admin-secret
data:
  DRIVER: cG9zdGdyZXM=
  POSTGRES_HOST: cG9zdGdyZXM=
  POSTGRES_PASSWD: cG9zdGdyZXM=
  POSTGRES_PORT: NTQzMg==
  POSTGRES_SSL: dHJ1ZQ==
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: admin-pod
spec:
  containers:
  - name: postgres-tester
    image: widmaster/postgres-provisionner
    command: [ "sh", "-c", "sleep 3600" ]
    envFrom:
      - secretRef:
          name: admin-secret
  restartPolicy: Never
