apiVersion: v1
metadata:
  name: admin-secret
data:
  DRIVER: "{{ .Values.databaseConfiguration.DRIVER | b64enc}}"
  PGHOST: "{{ .Values.databaseConfiguration.PGHOST | b64enc}}"
  PGPASSWORD: "{{ .Values.databaseConfiguration.PGPASSWORD | b64enc}}"
  PGPORT: "{{ .Values.databaseConfiguration.PGPORT | b64enc}}"
  PGSSLMODE: "{{ .Values.databaseConfiguration.PGSSLMODE | b64enc}}"
  PGUSER: "{{ .Values.databaseConfiguration.PGUSER | b64enc}}"
{{- range .Values.extraDatabaseConfiguration }}
  {{ .key }}: "{{ .value | b64enc}}"
{{- end }}   
kind: Secret
type: Opaque
