apiVersion: v1
data:
  databaseCreation.sql: | 
    DROP DATABASE IF EXISTS "${PGDATABASE_CREATE}";
    DROP ROLE IF EXISTS "${PGUSER_CREATE}";
    CREATE DATABASE "${PGDATABASE_CREATE}";
    CREATE ROLE "${PGUSER_CREATE}" WITH LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION PASSWORD '${PGPASSWORD_CREATE}';
    GRANT CONNECT ON DATABASE "${PGDATABASE_CREATE}" TO "${PGUSER_CREATE}";
    GRANT ALL PRIVILEGES ON DATABASE "${PGDATABASE_CREATE}" TO "${PGUSER_CREATE}";
  databaseDeletion.sql: | 
    DROP DATABASE IF EXISTS "${PGDATABASE_DELETE}";
    DROP ROLE IF EXISTS "${PGUSER_DELETE}";
  create-init-database: |
    #!/bin/sh
    export | grep PG
    envsubst < /cloudprov-scripts/databaseCreation.sql | psql -v ON_ERROR_STOP=1 postgres 
    psql -d "${PGDATABASE_CREATE}" -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp"'
  delete-database: |
    #!/bin/sh
    export | grep PG
    envsubst < /cloudprov-scripts/databaseDeletion.sql | psql -v ON_ERROR_STOP=1 postgres 
kind: ConfigMap
metadata:
  name: "cloudprov-scripts"
