apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudprov.fullname" . }}
  labels:
    a: cloudprov
    {{- include "cloudprov.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudprov.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudprov.selectorLabels" . | nindent 8 }}

    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cloudprov.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "NAME_LABEL"
              value: {{ include "cloudprov.name" . }}
            - name: "INSTANCE_LABEL"
              value: {{ .Release.Name }}
