
FROM golang:alpine AS builder
RUN apk add upx
WORKDIR /build
COPY go.mod go.sum /build/
RUN go mod download
COPY . .
RUN go install -ldflags="-s -w"
RUN upx /go/bin/cloudprov-controller


FROM alpine:3 AS runner
COPY --from=builder /go/bin/cloudprov-controller /usr/local/bin
CMD [ "/usr/local/bin/cloudprov-controller" ]
